### ISSUE TITLE
配置文件报错

### ISSUE THREAD

**Issue by Lemontree1851** [974758241/gw_ui5#1]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/40737457/204094626-d767b722-2d7e-4395-a05f-cb608cd23f4f.png">

**Comment by 974758241** [comment]
重启vscode试试,如果不行,说一下你操作系统,我是window上测试没有问题!

**Comment by Lemontree1851** [comment]
macOS Monterey 12.0.1，重启之后报错一样

**Comment by 974758241** [comment]
好的,我会之后测试macos 试试的
